### ISSUE TITLE
Part 3: HDFC Life Insurance does not show up in VPN & Device Management

### ISSUE THREAD

**Issue by byeoon** [WhySooooFurious/Ultimate-Sideloading-Guide#1]
After following the instructions very carefully, I wasn't able to find this part in my menu. The apps say they cannot be verified because of the integrity.

![image](https://github.com/user-attachments/assets/23f004e2-a81c-462f-bee7-28f1bfb92dbe)
![image](https://github.com/user-attachments/assets/8a25bec5-4961-4ca1-8e3b-c45841b1457a)

**Comment by WhySooooFurious** [comment]
I'm aware of this issue. I'm working on fixing it right now.

**Comment by byeoon** [comment]
Also one suggestion, On Part 2 Step 3 you should probably mention  to press 'Show Advanced Settings' because Full Trust won't show up unless you do that step (I'm on mobile so I had accidentally missed that the first time)

**Comment by Alanimdeo** [comment]
Is there a way to self-host files and install ESign?

**Comment by WhySooooFurious** [comment]
> Also one suggestion, On Part 2 Step 3 you should probably mention to press 'Show Advanced Settings' because Full Trust won't show up unless you do that step (I'm on mobile so I had accidentally missed that the first time)

I haven't actually encountered that, could you please send a screenshot?

**Comment by WhySooooFurious** [comment]
> Is there a way to self-host files and install ESign?

You can but you'll need to link the manifest.plist to the .ipa then create a itms_services link to the manifest.plist that installs the app.

**Comment by byeoon** [comment]
> > Also one suggestion, On Part 2 Step 3 you should probably mention to press 'Show Advanced Settings' because Full Trust won't show up unless you do that step (I'm on mobile so I had accidentally missed that the first time)
> 
> 
> 
> I haven't actually encountered that, could you please send a screenshot?


I might have been a little vague in that message, but you need to click these for the Full Trust to appear. Ik you had mentioned it in the guide but like I said before I was blind and completely missed it at first ![image](https://github.com/user-attachments/assets/c4c10c96-57dd-4c29-a29c-05eaf98141c9)![image](https://github.com/user-attachments/assets/7f799f96-fccc-44b0-8574-ca7db3ef8ba6)
(Hiding the dropdown and then downloading doesn't apply those settings? For some reason?? You have to click download while the dropdown is still visible)

**Comment by WhySooooFurious** [comment]
Oh! You meant that option, Yes thank you for that, I will incorporate it ASAP.

**Comment by BasharAy** [comment]
HDFC Life certificate has expired so it will no longer work. It expired around 10 days ago from memory.

**Comment by WhySooooFurious** [comment]
> HDFC Life certificate has expired so it will no longer work. It expired around 10 days ago from memory.

Yeah, I should probably check the all the certs and see if they're valid.

Thanks.
