### ISSUE TITLE
FIX FOR CHATGPT. tested, fully working. no revokes.

### ISSUE THREAD

**Issue by xkedude** [WhySooooFurious/Ultimate-Sideloading-Guide#10]
just add http://register.appattest.apple.com/ to your whitelist.
works with nextdns profile atleast.

credits: https://www.reddit.com/r/sideloaded/comments/1fkr3ly/unusual_activity_chatgpt_fix_for_dns_method/

**Comment by WhySooooFurious** [comment]
I know, I did have the NextDNS guide and included that as a whitelist but too many people don't read and didn't know about the 300000 query limit which got them revoked.

The redirect method that i'm using doesn't actually allow me to whitelist anything at all.

NextDNS unlimited query profile will be up in the next 2 weeks as well courtesy of the donations i've gotten.
