### ISSUE TITLE
Unable to verify the integrity

### ISSUE THREAD

**Issue by yrolgeht** [WhySooooFurious/Ultimate-Sideloading-Guide#11]
Hello, yesterday i successfully managed to follow the guide and installed a few apps with Esign, but today i was installing the Feather from the guide and i got "Unable to install/integrity could not be verified" after trying to sign random app with Feather. After that i'm not able to sign any app with Esign anymore but the apps that was previous installed are perfect working. Should i make the Backup/Reset Method?

**Comment by WhySooooFurious** [comment]
Feather doesn't work for some reason.

You can try another certificate if you uninstall ESign and the other apps, if that doesn't work then you gotta backup and restore.
