### ISSUE TITLE
Apps get revoked

### ISSUE THREAD

**Issue by dylans509** [WhySooooFurious/Ultimate-Sideloading-Guide#12]
So I shutted off my iPhone and the apps got revoked meaning I couldn’t sign them, so I had to delete all the things on the tutorial and re do it. Is there anything I could do so if I shut down my phone the apps are still signed?

**Comment by WhySooooFurious** [comment]
It shouldn't revoke on restart at all!

You definitely got revoked before.

**Comment by dylans509** [comment]
But it was my 1st time trying the ur tutorial tho and I shut down my phone because the whole phone froze and I tried to open ESign and it didn’t open and all the apps I side loaded were not verified Sent from my iPhoneOn Nov 3, 2024, at 11:16 PM, WhySooooFurious ***@***.***> wrote:﻿
It shouldn't revoke on restart at all!
You definitely got revoked before.

**Comment by WhySooooFurious** [comment]
Cool, your phone freezing may have caused a dns leak, if you phone freezes again I recommend you force restart your phone as seen [here](https://support.apple.com/en-au/guide/iphone/iph8903c3ee6/ios)

**Comment by dylans509** [comment]
Yeah Ik how to force boot, so I just try that instead of shutting down?Sent from my iPhoneOn Nov 3, 2024, at 11:43 PM, WhySooooFurious ***@***.***> wrote:﻿
Cool, your phone freezing may have caused a dns leak, if you phone freezes again I recommend you force restart your phone as seen here

**Comment by WhySooooFurious** [comment]
idk, shutting down and restarting works for a lot of people, I restart all the time

**Comment by dylans509** [comment]
Alr but what if my phone dies?Sent from my iPhoneOn Nov 3, 2024, at 11:54 PM, WhySooooFurious ***@***.***> wrote:﻿
idk, shutting down and restarting works for a lot of people, I restart all the time

**Comment by WhySooooFurious** [comment]
idk, shutting down and restarting works for a lot of people, I restart all the time
