### ISSUE TITLE
Reboot may cause apps to be revoked

### ISSUE THREAD

**Issue by aquirozc** [WhySooooFurious/Ultimate-Sideloading-Guide#13]
While the FAQ states that a simple restart is not enough to bypass this entire procedure and cause apps to be revoked, my own research suggests this may not be always true on older or lower-performance devices (such as 5-year-old A11 phones).

I've noticed that to effectively prevent arbitrary app revocation, these two steps must be accomplished

- Enabling Airplane Mode and disabling Wi-Fi before shutting down the phone
- Launch at least one enterprise-signed app for each device boot

I'd appreciate  if you update the FAQ to spread out this findings.

**Comment by WhySooooFurious** [comment]
You might just be right, I've tested on my 16pm, 15pm , 11 and 8 Plus and have found no issues.

I will still add this to the FAQ and Post Install guide just to be safe, Thanks.
