### ISSUE TITLE
Can't see the WSF config in VPN & Device Management

### ISSUE THREAD

**Issue by ArvTheCarve** [WhySooooFurious/Ultimate-Sideloading-Guide#17]
I'm trying to switch to the maDNS config but can't get rid of the old one, it doesn't show up in the vpn and device management section for me to delete the profile.

![image](https://github.com/user-attachments/assets/90760a77-a833-4148-8c45-e72ea0bbd167)![image](https://github.com/user-attachments/assets/7c3655ce-4ebc-4f5e-9781-2cd0bc0e18eb)![image](https://github.com/user-attachments/assets/e32ef383-f1b7-4189-bcbe-fe559fe629c1)

**Comment by WhySooooFurious** [comment]
Should've used the workaround for Nugget and Cowabunga. 

Will only be removed with a full reset.

**Comment by ArvTheCarve** [comment]
> Should've used the workaround for Nugget and Cowabunga. 
> 
> 
> 
> Will only be removed with a full reset.

Ohh, I did use cowabunga. Thanks man!
