### ISSUE TITLE
Esign version used?

### ISSUE THREAD

**Issue by BasharAy** [WhySooooFurious/Ultimate-Sideloading-Guide#2]
It’s unclear which esign version does your downloads use. 
I believe latest offical is 5.0.2. But latest no logs version is 5.0.0. It’s better to link to no logs version if not done already.

**Comment by WhySooooFurious** [comment]
I have 5.0.2.

I would rather have the latest ESign.

The dns addresses to block ESign logs are provided.

**Comment by BasharAy** [comment]
My concern that this will use more requests on nextdns and possibly cause it to hit the 300k limit faster. It really depends on how many times does esign call home.

**Comment by WhySooooFurious** [comment]
> My concern that this will use more requests on nextdns and possibly cause it to hit the 300k limit faster. It really depends on how many times does esign call home.

Well you are right.

It is minimal though. Won't really affect the 300k queries at the end of the day unless you spend all day on it.
