### ISSUE TITLE
It doesn't install enterprise certificates or even try

### ISSUE THREAD

**Issue by dlmckinney1988** [WhySooooFurious/Ultimate-Sideloading-Guide#3]
I've rest using every method and I can't get anything to work. I've use dns method and the regular method. I had dns method working on 17.7 but am on 18.1B3 and nothing. ![image](https://github.com/user-attachments/assets/60e2e6e4-177a-4154-b473-340e6ce24725) some help maybe?

**Comment by dlmckinney1988** [comment]
![image](https://github.com/user-attachments/assets/cc1a2944-d466-41ba-80ad-bd5a14e041b4)

**Comment by WhySooooFurious** [comment]
Betas might have issues, I recommend updating to 18.1RC and fully resetting your phone.

**Comment by WhySooooFurious** [comment]
This is actually a known issue, It seems the certificiates are simple down for some reason.

Some still work, such as Anbang, Henan, Sunshine, VietnamPost and Continental.
