### ISSUE TITLE
Copy paste

### ISSUE THREAD

**Issue by PuReEnVyUs** [WhySooooFurious/Ultimate-Sideloading-Guide#5]
Seems like I’ve seen this guide before…

would have at least appreciated a mention sense it’s almost a copy paste of my guide..

https://www.reddit.com/u/PuReEnVyUs/s/7vRoMXno6D

**Comment by WhySooooFurious** [comment]
Lol, this isn't a copy and paste of your guide at all.

Only thing I probably copied is the manifest.plist from khoindvn's site and edited that.

Be less full of yourself next time.

**Comment by WhySooooFurious** [comment]
No way bros tryna say that the steps on how to fucking use esign in the first place is a copy of his guide 😭😭😭😂

**Comment by PuReEnVyUs** [comment]
Avieshik copied my guide originally - on the khoindvn website plus updated it for over a year. Seems like you’re mad you got called out and even edited the URL because you don’t want people to see it. Just take the L

**Comment by WhySooooFurious** [comment]
Like I said, I haven't used your guide or that guy's guide.

I removed the link, because that's just blatant advertising lol.

I'm not taking any L.

Go back to your shitty google docs guide and link everything from other services LMAO.
