### ISSUE TITLE
unable to install app iphone integrity could not be verified

### ISSUE THREAD

**Issue by seyed-sabbagh** [WhySooooFurious/Ultimate-Sideloading-Guide#6]
I hope you're doing well. I am trying to install an esign app on my iPhone14 (iOS 17.5), but I keep encountering the following error message:

"Unable to install Esign . Integrity could not be verified."

Could you please assist me in resolving this issue? I have tried restarting my device, but the problem persists.

Looking forward to your guidance.

**Comment by WhySooooFurious** [comment]
Revoked.
Read the guide.

**Comment by seyed-sabbagh** [comment]
When I enable the DNS, my phone has no internet access at all. I can’t even open the application that gets created after installing the profile.
Is the problem related to the DNS setup, or is everything okay?

**Comment by WhySooooFurious** [comment]
> When I enable the DNS, my phone has no internet access at all. I can’t even open the application that gets created after installing the profile. Is the problem related to the DNS setup, or is everything okay?

This might be an problem you have with your internet provider? Can't really say anything.
