### ISSUE TITLE
all apps modified by e-sign crash on start

### ISSUE THREAD

**Issue by byeoon** [WhySooooFurious/Ultimate-Sideloading-Guide#9]
there is no error message, they all just crash whenever i try to open them. this has never happened before https://github.com/user-attachments/assets/6b6af3e1-15d5-4b2d-8db6-d5f64918bb1c

not sure if this is the correct place to report this but idk why it's happening

**Comment by WhySooooFurious** [comment]
This is the right place to post issues, does ESign crash as well?

**Comment by byeoon** [comment]
i would assume it has to do with certs being revoked(or not added properly?), because when trying to reinstall using the Anbang, Henan, and VitenamPost certs, it gives me an error.

**Comment by WhySooooFurious** [comment]
Yeah, that's revoked now.

**Comment by byeoon** [comment]
> Yeah, that's revoked now.

is there a fix or new certs coming out soon?

**Comment by WhySooooFurious** [comment]
Either wait 1-2 weeks for me, or follow the revoked guide.
